#title: Claudio Sasseron
#logo:
#description:
#show_dowloads: true
#theme: jekyll-theme-minimal

title: Claudio Sasseron
description: Quality and Continuous Improvement Specialist | AI & Data-Driven Process Optimization
url: "https://github.com/Sasseron"  
#baseurl: ""  
theme: jekyll-theme-minimal
plugins:
  - jekyll-remote-theme
stylesheets:
  - /assets/styles.css
show_downloads: true

github_username: Sasseron
linkedin_username: www.linkedin.com/in/claudio-sasseron
email: claudio.sasseron@gmail.com 

footer:
  message: "Let’s connect and collaborate!"
  links:
    - label: "GitHub"
      icon: "github"
      url: "https://github.com/Sasseron"
    - label: "LinkedIn"
      icon: "linkedin"
      url: "https://www.linkedin.com/in/claudio-sasseron"
    - label: "Email"
      icon: "envelope"
      url: "mailto:your-email@example.com"
